
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "2-1-stable"
  name = "github.com/buildkite/agent"

[[constraint]]
  name = "github.com/hashicorp/hil"
  revision = "3eb5226cd1c40e1788b3295b5bafb5a2fcac90a6"

[[constraint]]
  branch = "v26"
  name = "gopkg.in/libgit2/git2go.v26"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
